apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: briitz
spec: 
  selector:
    app: payment    
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
      